version: '3.8'

services:
  jessjessbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jessjessbot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - BOT_ID=${BOT_ID}
      - ROLE_ID=${ROLE_ID}
      - GUILD_ID=${GUILD_ID}
      - DB_FILE_NAME=data/wordle_stats.db
      - NODE_ENV=production
      - RIOT_API_KEY=${RIOT_API_KEY}
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
