version: '3.8'

services:
  jessjessbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jessjessbot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - BOT_ID=${BOT_ID}
      - ROLE_ID=${ROLE_ID}
      - GUILD_ID=${GUILD_ID}
      - DB_FILE_NAME=/app/data/wordle_stats.db
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    restart: unless-stopped
